export type Teacher = {
  id: number;
  name: string;
  email: string;
  phone: string;
  subject: string;
  status: "active" | "inactive";
  address: string;
  joiningDate: string;
  gender: "male" | "female" | "other";
  experience: string;
  photoUrl: string;
  paymentStatus: "paid" | "unpaid";
  amount: number;
  lastPayment: string;
  avatar: string;
};
export const teachers: Teacher[] = [
  {
    id: 1,
    name: "Ishita Sharma",
    email: "ishita.sharma@example.com",
    phone: "+91 9876543210",
    subject: "Biology",
    status: "active",
    address: "123 Green Avenue, Pune",
    joiningDate: "2023-01-15",
    gender: "female",
    experience: "3 years",
    photoUrl: "/avatar1.jpg",
    paymentStatus: "unpaid",
    amount: 4000,
    lastPayment: "2025-05-25",
    avatar: "/avatar1.jpg",
  },
  {
    id: 2,
    name: "Vivaan Reddy",
    email: "vivaan.reddy@example.com",
    phone: "+91 9988776655",
    subject: "Chemistry",
    status: "inactive",
    address: "21 MG Road, Hyderabad",
    joiningDate: "2022-09-10",
    gender: "male",
    experience: "4 years",
    photoUrl: "/avatar2.jpg",
    paymentStatus: "unpaid",
    amount: 4000,
    lastPayment: "2025-06-06",
    avatar: "/avatar2.jpg",
  },
  {
    id: 3,
    name: "Reyansh Kapoor",
    email: "reyansh.kapoor@example.com",
    phone: "+91 8866445522",
    subject: "Biology",
    status: "active",
    address: "78 Rose Lane, Jaipur",
    joiningDate: "2021-07-20",
    gender: "male",
    experience: "5 years",
    photoUrl: "/avatar1.jpg",
    paymentStatus: "unpaid",
    amount: 3000,
    lastPayment: "2025-06-21",
    avatar: "/avatar1.jpg",
  },
  {
    id: 4,
    name: "Diya Reddy",
    email: "diya.reddy@example.com",
    phone: "+91 9090909090",
    subject: "Chemistry",
    status: "inactive",
    address: "50 Lakeview, Bangalore",
    joiningDate: "2020-12-01",
    gender: "female",
    experience: "6 years",
    photoUrl: "/avatar2.jpg",
    paymentStatus: "unpaid",
    amount: 2500,
    lastPayment: "2025-06-16",
    avatar: "/avatar2.jpg",
  },
  {
    id: 5,
    name: "Arjun Nair",
    email: "arjun.nair@example.com",
    phone: "+91 9012345678",
    subject: "History",
    status: "active",
    address: "88 Temple Street, Kochi",
    joiningDate: "2022-03-12",
    gender: "male",
    experience: "2 years",
    photoUrl: "/avatar1.jpg",
    paymentStatus: "paid",
    amount: 3000,
    lastPayment: "2025-06-20",
    avatar: "/avatar1.jpg",
  },
  {
    id: 6,
    name: "Sneha Patil",
    email: "sneha.patil@example.com",
    phone: "+91 9871234560",
    subject: "Mathematics",
    status: "active",
    address: "12 Sunrise Colony, Mumbai",
    joiningDate: "2023-04-05",
    gender: "female",
    experience: "2 years",
    photoUrl: "/avatar2.jpg",
    paymentStatus: "unpaid",
    amount: 4000,
    lastPayment: "2025-06-24",
    avatar: "/avatar2.jpg",
  },
  {
    id: 7,
    name: "Myra Deshmukh",
    email: "myra.deshmukh@example.com",
    phone: "+91 9988772233",
    subject: "English",
    status: "inactive",
    address: "44 Hill Top, Nagpur",
    joiningDate: "2021-11-11",
    gender: "female",
    experience: "3.5 years",
    photoUrl: "/avatar1.jpg",
    paymentStatus: "unpaid",
    amount: 3000,
    lastPayment: "2025-06-28",
    avatar: "/avatar1.jpg",
  },
  {
    id: 8,
    name: "Kabir Kapoor",
    email: "kabir.kapoor@example.com",
    phone: "+91 9123456780",
    subject: "Economics",
    status: "active",
    address: "99 GT Road, Delhi",
    joiningDate: "2022-08-22",
    gender: "male",
    experience: "3 years",
    photoUrl: "/avatar2.jpg",
    paymentStatus: "paid",
    amount: 4500,
    lastPayment: "2025-07-08",
    avatar: "/avatar2.jpg",
  },
  {
    id: 9,
    name: "Aarav Singh",
    email: "aarav.singh@example.com",
    phone: "+91 9765432180",
    subject: "Physics",
    status: "active",
    address: "16 Station Road, Lucknow",
    joiningDate: "2023-05-19",
    gender: "male",
    experience: "1 year",
    photoUrl: "/avatar1.jpg",
    paymentStatus: "paid",
    amount: 3200,
    lastPayment: "2025-06-15",
    avatar: "/avatar1.jpg",
  },
  {
    id: 10,
    name: "Anaya Sharma",
    email: "anaya.sharma@example.com",
    phone: "+91 9080706050",
    subject: "History",
    status: "inactive",
    address: "7 Park Lane, Chandigarh",
    joiningDate: "2021-06-30",
    gender: "female",
    experience: "4 years",
    photoUrl: "/avatar2.jpg",
    paymentStatus: "unpaid",
    amount: 3200,
    lastPayment: "2025-07-10",
    avatar: "/avatar2.jpg",
  },
];
